# Generated by Django 5.1.3 on 2024-11-21 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mass', '0008_remove_medication_stock_quantity_medication_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medication',
            name='stock_quantity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='phone_number',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_address',
            field=models.CharField(default='', max_length=255),
        ),
    ]
