# Generated by Django 5.1.3 on 2024-11-22 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mass', '0009_medication_stock_quantity_order_phone_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
