# Generated by Django 5.1.2 on 2024-12-28 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mass', '0020_extendeduser_is_doctor'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='quantities',
            field=models.JSONField(blank=True, default='[]'),
        ),
    ]
