# Generated by Django 5.1.2 on 2024-12-29 14:36

import mass.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mass', '0024_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='expiry_date',
            field=models.DateField(default=mass.models.default_expiry_date),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('paid', 'Paid'), ('pending', 'Pending'), ('received', 'Received'), ('expired', 'Expired')], default='paid', max_length=10),
        ),
    ]
