# Generated by Django 5.1.2 on 2024-11-17 11:15

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(default='null')),
                ('side_effects', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('stock_quantity', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_order', models.DateField(default=datetime.datetime.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('medication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mass.medication')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mass.order')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='contents',
            field=models.ManyToManyField(through='mass.OrderItem', to='mass.medication'),
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prescription_ID', models.DecimalField(decimal_places=0, max_digits=4)),
                ('patient_name', models.CharField(max_length=255)),
                ('date_prescribed', models.DateField(default=datetime.datetime.now)),
                ('dosage', models.CharField(max_length=100, null=True)),
                ('medications', models.ManyToManyField(to='mass.medication')),
            ],
        ),
        migrations.CreateModel(
            name='ExtendedUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('user_orders', models.ManyToManyField(blank=True, to='mass.order')),
                ('prescriptions', models.ManyToManyField(blank=True, to='mass.prescription')),
            ],
        ),
    ]
