# Generated by Django 5.1.3 on 2024-11-17 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mass', '0003_remove_extendeduser_cart_cartitem_cart_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medication',
            name='stock_quantity',
        ),
        migrations.AddField(
            model_name='medication',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media\\image'),
        ),
        migrations.AlterField(
            model_name='medication',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='medication',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='medication',
            name='side_effects',
            field=models.CharField(max_length=200),
        ),
    ]
