# Generated by Django 5.1.3 on 2024-11-18 16:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mass', '0005_cart_user_alter_medication_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extendeduser',
            name='cart',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mass.cart'),
        ),
    ]
