# Generated by Django 5.1.3 on 2024-11-23 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mass', '0011_order_status_alter_orderitem_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='method_of_payment',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='order',
            name='phone_number',
            field=models.DecimalField(decimal_places=0, max_digits=9),
        ),
    ]
