# Generated by Django 5.1.3 on 2024-11-23 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mass', '0012_order_method_of_payment_alter_order_phone_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='method_of_payment',
            new_name='payment_method',
        ),
    ]
