# Generated by Django 5.1.2 on 2024-12-03 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mass', '0014_remove_prescription_dosage'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='realized',
            field=models.BooleanField(default=False),
        ),
    ]
