# Generated by Django 5.1.2 on 2024-12-03 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mass', '0015_prescription_realized'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='added',
            field=models.BooleanField(default=False),
        ),
    ]
