# Generated by Django 5.1.2 on 2024-12-03 20:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mass', '0016_prescription_added'),
    ]

    operations = [
        migrations.AddField(
            model_name='extendeduser',
            name='prescription_cart',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prescription_user_cart', to='mass.cart'),
        ),
        migrations.AlterField(
            model_name='extendeduser',
            name='cart',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_cart', to='mass.cart'),
        ),
    ]
