# Generated by Django 5.1.2 on 2024-12-28 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mass', '0019_remove_order_payment_method_extendeduser_is_manager_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='extendeduser',
            name='is_doctor',
            field=models.BooleanField(default=False),
        ),
    ]
