# Generated by Django 5.1.2 on 2024-12-28 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mass', '0021_prescription_quantities'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescription',
            name='quantities',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
    ]
