# Generated by Django 5.1.2 on 2024-12-29 13:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mass', '0022_alter_prescription_quantities'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicationStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('reserved', models.PositiveIntegerField(default=0)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mass.location')),
                ('medication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mass.medication')),
            ],
            options={
                'unique_together': {('medication', 'location')},
            },
        ),
    ]
