# Generated by Django 5.1.2 on 2024-12-29 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mass', '0023_medicationstock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('paid', 'Paid'), ('pending', 'Pending'), ('received', 'Received')], default='paid', max_length=10),
        ),
    ]
