# Generated by Django 5.1.3 on 2024-12-30 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mass', '0025_order_expiry_date_alter_order_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Symptom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('advice', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='medication',
            name='symptoms',
            field=models.ManyToManyField(related_name='medications', to='mass.symptom'),
        ),
    ]
