# Generated by Django 5.1.3 on 2025-01-09 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mass', '0027_alter_order_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medication',
            name='stock_quantity',
        ),
    ]
