# Generated by Django 5.1.3 on 2025-01-09 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mass', '0028_remove_medication_stock_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medication',
            name='symptoms',
        ),
    ]
